language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t sakirahassan/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sakirahassan/docker-react npm run test

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-317448010203"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY